# Generated by Django 5.2.14 on 2026-05-15 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parent_category",
                    models.CharField(
                        help_text="대분류 (예: IT/기술, 인문/역사)", max_length=50
                    ),
                ),
                (
                    "sub_category",
                    models.CharField(
                        help_text="소분류 관심사 (예: 반도체, 요리)",
                        max_length=50,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "관심사 카테고리",
                "verbose_name_plural": "관심사 카테고리 목록",
            },
        ),
        migrations.CreateModel(
            name="DailyLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "raw_text",
                    models.TextField(
                        blank=True,
                        help_text="사용자가 직접 입력한 일상 텍스트",
                        null=True,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="logs/%Y/%m/%d/"
                    ),
                ),
                (
                    "detected_object",
                    models.CharField(
                        blank=True,
                        help_text="AI 비전 엔진이 인식한 물체 이름",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "tmi_content",
                    models.TextField(
                        blank=True,
                        help_text="실시간으로 요약된 사용자 맞춤형 2줄 TMI",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="기록 생성 일시"),
                ),
                (
                    "matched_category",
                    models.ForeignKey(
                        blank=True,
                        help_text="TMI 컨텍스트 매칭에 사용된 유저의 관심사 소분류",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interests",
                    models.ManyToManyField(
                        blank=True, related_name="interested_users", to="api.category"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
